services:
  notification-service:
    build: .
    container_name: notification-service
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
      - APPLICATION_NAME=notification-service
      - POSTGRES_DB=notification_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - notification_db
      - flyway
    networks:
      - default
      - store-network

  notification_db:
    image: postgres:15-alpine
    container_name: notification_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notification_db
    ports:
      - "5434:5432"
    volumes:
      - notification_db_data:/var/lib/postgresql/data
    networks:
      - default

  flyway:
    image: flyway/flyway
    container_name: notification_flyway
    command: -url=jdbc:postgresql://notification_db:5432/notification_db -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - notification_db
    networks:
      - default

  pgadmin_notification:
    image: dpage/pgadmin4
    container_name: pgadmin_notification
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5052:80"
    depends_on:
      - notification_db
    networks:
      - default

volumes:
  notification_db_data:

networks:
  store-network:
    external: true