services:
  notification_db:
    image: postgres:17
    restart: always
    env_file: ".env"
    volumes:
      - notification_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - store-network

  flyway:
    image: flyway/flyway:11.12
    depends_on:
      notification_db:
        condition: service_healthy
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    command: >
      -url=jdbc:postgresql://notification_db:5432/$POSTGRES_DB
      -user=$POSTGRES_USER
      -password=$POSTGRES_PASSWORD
      migrate
    env_file: ".env"
    networks:
      - store-network

  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      notification_db:
        condition: service_healthy
    env_file: ".env"
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src:/app/src
      - ~/.m2:/root/.m2
    networks:
      - store-network

  pgadmin_notification:
    image: dpage/pgadmin4:9.8.0
    restart: always
    env_file: ".env"
    depends_on:
      notification_db:
        condition: service_healthy
    ports:
      - "7779:80"
    volumes:
      - pgadmin_notification_data:/var/lib/pgadmin
    networks:
      - store-network

volumes:
  notification_db_data:
  pgadmin_notification_data:

networks:
  store-network:
    external: true